import React from 'react';
import Link from 'next/link';
import { FiArrowUpRight } from "react-icons/fi";

type ProjectItemProps = {
  title: string;
  description: string;
  gitHubLink: string;
  tags: string[];
};

const ProjectItem: React.FC<ProjectItemProps> = ({ title, description, gitHubLink, tags }) => {
  return (
    <Link href={gitHubLink} passHref className='group'>
        <div className="mb-4">
          <h2 className="text-2xl font-bold mb-2 flex justify-between">
            <div className="title transition duration-300 ease-in-out group-hover:text-text-primary">{title}</div>
            <div className="arrow">
              <FiArrowUpRight className='transition duration-300 ease-in-out group-hover:text-text-primary' />
            </div>
          </h2>
          <p className="mb-2 sm:text-xl text-base">{description}</p>
          <div className="flex flex-wrap space-x-2">
            {tags.map((tag, index) => (
              <span key={index} className="text-sm text-text-primary">
                {tag}
              </span>
            ))}
          </div>
        </div>
    </Link>
  );
};

const Projects = () => {
  const projects = [
    { title: "Traffic Congestion Reduction", description: "Utilizing reinforcement learning, this project aims to minimize traffic jams at intersections, complete with dynamic visualizations using Pygame.", gitHubLink: "https://github.com/praneethravuri/traffic-congestion-reduction-with-SARSA", tags: ["Python", "Pygame", "AI"] },
    { title: "OpenLLMs", description: "A chat app where users can ask questions and get answers from pre-trained open-source language models. The app has a chat interface for users to type their questions, and it replies with answers generated by the selected models.", gitHubLink: "https://github.com/praneethravuri/open-llms", tags: ["Gen AI", "LLM", "ML"] },
    { title: "Job Tools", description: "A suite of automation scripts designed to enhance your LinkedIn networking and streamline email correspondence.", gitHubLink: "https://github.com/praneethravuri/jobs-tools", tags: ["JavaScript", "Python"] },
    { title: "Amazon Product Information Scraper", description: "Easily extract detailed product information from Amazon with this efficient web scraping bot, leveraging Selenium and Python.", gitHubLink: "https://github.com/praneethravuri/Amazon-Product-Information-Scraper", tags: ["Selenium", "Python"] },
  ];

  return (
    <div className="p-2 border-b-2 border-white">
      <div className="title">
        <p className="sm:text-4xl text-2xl font-bold text-text-primary">Projects</p>
      </div>
      <div className="mt-4">
        {projects.map((project, index) => (
          <ProjectItem
            key={index}
            title={project.title}
            description={project.description}
            gitHubLink={project.gitHubLink}
            tags={project.tags}
          />
        ))}
      </div>
    </div>
  );
}

export default Projects;
